apiVersion: v1
kind: Secret
metadata:
  name: skillrec-secrets
  namespace: skillrec
type: Opaque
data:
  # Base64 encoded GROQ_API_KEY (you need to encode your actual key)
  # echo -n "your-groq-api-key" | base64
  GROQ_API_KEY: Z3NrX0hQRVBNaEhndU9pTHE5VVlwUVpuV0dkeWIzRllWdFBhQUNuS0tTSjhyQ3A3Y2pXbWM1U0c=